# Generated by Django 5.1.3 on 2024-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(to='tracker.type'),
        ),
    ]
