# Generated by Django 5.1.3 on 2024-12-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_issue_type_issue_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='types',
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.type'),
        ),
    ]
