# Generated by Django 5.1.3 on 2024-12-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_fill_project_in_issues'),
        ('tracker', '0006_project_created_at_project_updated_at'),
    ]

    operations = [
    ]
