# Generated by Django 5.1.3 on 2024-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_merge_20241222_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(related_name='issues', to='tracker.type', verbose_name='Типы'),
        ),
    ]
