# Generated by Django 5.1.3 on 2025-01-05 07:30

from django.conf import settings
from django.db import migrations, models

from django.contrib.auth.models import Group, Permission

def create_groups(apps, schema_editor):
    manager_group, _ = Group.objects.get_or_create(name='Менеджер проекта')
    lead_group, _ = Group.objects.get_or_create(name='Капитан')
    dev_group, _ = Group.objects.get_or_create(name='Разработчик')

    permissions = Permission.objects.all()

    manager_permissions = [
        permissions.filter(codename__in=['add_project', 'change_project', 'delete_project']),
        permissions.filter(codename__in=['add_task', 'change_task', 'delete_task']),
        permissions.filter(codename__in=['add_user', 'remove_user']),
    ]
    manager_group.permissions.set(manager_permissions)

    lead_permissions = [
        permissions.filter(codename__in=['add_task', 'change_task', 'delete_task']),
        permissions.filter(codename__in=['add_user', 'remove_user']),
    ]
    lead_group.permissions.set(lead_permissions)

    dev_permissions = [
        permissions.filter(codename__in=['add_task', 'change_task']),
    ]
    dev_group.permissions.set(dev_permissions)

def create_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    manager_user = User.objects.create_user(username='manager', password='manager')
    manager_user.groups.add(Group.objects.get(name='Менеджер проекта'))

    lead_user = User.objects.create_user(username='lead', password='lead')
    lead_user.groups.add(Group.objects.get(name='Капитан'))

    dev_user = User.objects.create_user(username='dev', password='dev')
    dev_user.groups.add(Group.objects.get(name='Разработчик'))



class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_issue_options_issue_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
